### ISSUE TITLE
When integrated with SwiftPM, headers are included in the build product

### ISSUE THREAD

**Issue by salling** [comScore/Comscore-Swift-Package-Manager#1]
This should not be necessary, and isn't the case when Cocoapods is used for integration.

![Screenshot 2021-02-23 at 00 04 38](https://user-images.githubusercontent.com/1453580/108781935-fc037400-756a-11eb-9dff-593996a261bf.png)

**Comment by markoocko** [comment]
Hi Jonas,
Can you please elaborate a bit more. Why would included headers be an issue in the first place? And to reply to your comment above..CocoaPods also uses *.framework files which have headers included in them. As far as we know, these headers are essential for the library integration to any type of project. If you propose another way, please let us know and we will consider it.

**Comment by salling** [comment]
> Hi Jonas,
> Can you please elaborate a bit more. Why would included headers be an issue in the first place? And to reply to your comment above..CocoaPods also uses *.framework binaries which have headers included in them. As far as we know, these headers are essential for the library integration to any type of project. If you propose another way, please let us know and we will consider it.

The problem, as I see it, is that the headers are included in the final built product. The headers are only needed at build time, and we want to avoid shipping irrelevant stuff in the IPA.

I checked another Swift package that contains a binaryTarget `.framework` (PSPDFKit) and it suffers from the same problem.

Looks like the cause of this problem is Xcode/SwiftPM.

**Comment by salling** [comment]
I think building your library **statically** and wrapping it in an xcframework would result in headers not being distributed. At least that's what we're seeing in other Swift packages that we integrate with. But I suppose that may come with its own drawbacks.
