### ISSUE TITLE
JUCE leak detection assertions make unit testing on tvOS unnecessarily painful

### ISSUE THREAD

**Issue by defagos** [comScore/Comscore-Swift-Package-Manager#15]
Hi,

When running a tvOS test target using comScore in debug mode, the debugger is paused when the following internal assertions are raised:

```
*** Leaked objects detected: 1 instance(s) of class Session
JUCE Assertion failure in juce_LeakedObjectDetector.h:92
```

This makes running unit tests for a target using comScore unnecessary painful on tvOS.

# How to reproduce

Here is a Swift package using comScore 6.11.0. It simply provides a `Tracker` class instantiating comScore in some basic way. A unit test creates an instance of this `Tracker` without doing anything else.

[AnnoyingJuce.zip](https://github.com/comScore/Comscore-Swift-Package-Manager/files/13842189/AnnoyingJuce.zip)

To reproduce the issue:

1. Open the Package.swift manifest with Xcode 15.
2. Run the unit tests on iOS. Everything works fine.
3. Run the unit tests on tvOS. The debugger is paused on the assertion listed above.

# Workaround

The tvOS tests can be run in release mode to silent the assertion. This is suitable when running tests on a CI server, but not for debugging code step by step during development.

**Comment by nabi-cs** [comment]
Hi @defagos ,

Thanks for reporting this issue. We will try to find out the reason behind that and come back to you as soon as possible.

Best regards,
Nabi

**Comment by wroberts-comscore** [comment]
v6.12.2 resolves this issue
