### ISSUE TITLE
Add Privacy Manifest

### ISSUE THREAD

**Issue by debadaracco** [comScore/Comscore-Swift-Package-Manager#16]
Feature Request Privacy Manifest

Apple introduced the Privacy Manifest at the WWDC 2023. This makes it easy for developers to report the data SDKs collect to Apple. Additionally, it is necessary to report the use of Required Reason APIs in the Privacy Manifest. It would be great, if ComScore could add a Privacy Manifest that reports the data, which is collected by the framework.

Apple Links:
[Privacy Manifest Overview](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files)
[Required Reason API Overview](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)

**Comment by RoblesJ** [comment]
Any updates on this?
