### ISSUE TITLE
visionOS support

### ISSUE THREAD

**Issue by defagos** [comScore/Comscore-Swift-Package-Manager#17]
Hi,

Now that visionOS is officially available in the US it would certainly be valuable to provide support for it. Is this somewhere on your roadmap?

Thanks in advance.

**Comment by waliid** [comment]
Hi, any news about this issue?

**Comment by spengel** [comment]
Thanks for asking about this topic as it is a good way to understand interest. We have spoken with product and aligned that until we have more client demand for the measurement of visionOS apps in our client facing products, we will not be supporting data collection/development targeting visionOS.
