### ISSUE TITLE
Unable to submit binaries to Apple if embedding comScore 6.12.0

### ISSUE THREAD

**Issue by defagos** [comScore/Comscore-Swift-Package-Manager#19]
Hi,

The [zipped framework provided for v6.12.0 Swift Package integration](https://github.com/comScore/Comscore-Swift-Package-Manager/releases/download/v6.12.0/ComScore.xcframework.zip) incorrectly contains the unsigned `strip-framework.sh` script:

<img width="320" alt="Screenshot 2024-03-10 at 11 29 29" src="https://github.com/comScore/Comscore-Swift-Package-Manager/assets/170201/182535b5-d7ba-4a75-9287-dcea93ee558f">

As a result submission of the binaries to App Store Connect fails with an error:

```
[Application Loader Error Output]: ERROR: [ContentDelivery.Uploader] Asset validation failed (90035) Invalid Signature. Code object is not signed at all. The file at path “MyApp.app/Frameworks/ComScore.framework/strip-framework.sh” is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose “Clean All” in Xcode, delete the “build” directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/support/code-signing.
```

Inclusion of the script in this kind of product is likely an oversight. Thanks in advance for removing it.

**Comment by wroberts-comscore** [comment]
v6.12.2 resolves this issue

**Comment by defagos** [comment]
Thank you very much for the quick fix!
