### ISSUE TITLE
Xcode takes a long time to load the package and builds fail when switching branches

### ISSUE THREAD

**Issue by chrispomeroyhale** [comScore/Comscore-Swift-Package-Manager#2]
I am happy to see SPM support! However, ever since my team has switched this dependency to SPM we've been having trouble building our project. Sometimes it takes a long time for this package to load. Sometimes it gets stuck. Every time I check out a branch, Xcode reloads our packages, and I get this error:

`artifact of binary target 'ComScore' failed extraction: The operation couldn’t be completed. (TSCBasic.StringError error 1.)`

followed by:

`"Missing package product 'ComScore'"`

This can be fixed by restarting Xcode and cleaning the build before rebuilding. I encounter this on Xcode 12.2 as well as 12.4 which we are transitioning to.

Although it's possible a future version of Xcode may help to remedy this, we don't encounter this with our other seven packages. I suspect this is because it uses a pre-compiled framework. It looks like SPM clones the repo which in this case is on the larger side since it contains these framework binaries. Then the Package.swift makes an additional download from Github with the framework it wants to use.

Is there anything you can do to speed up package retrieval?

**Comment by markoocko** [comment]
Hi Chris, 

Thank you for reporting the issue. We took a look and you're correct. The 'ComScore.xcframework.zip' file in the root of the repo was not explicitly necessary for the SPM workflow, so therefore it was removed, which should make the checkout faster. 

Although, when testing switching between different versions of our SPM package, we actually encoutered your exact error message. While analyzing the issue, we've seen that the error is thrown after the GitHub repo was already succesfully cloned. So therefore we can assume that the size of the repo is not the issue, but rather a xcode bug. 

What we found to solve this issue (alongside your solution) was to completly remove:
-  our SPM package, found under the "Swift Packages" project tab
-  the Comscore library from the "Frameworks, libraries and embedded content" list under the Project -> Target -> General tab
- and the local checkout of our SPM GitHub repo. Example path: /Users/username/Library/Developer/Xcode/DerivedData/Hello_World-epkzhvjtrffoksfxtjqnummefabo/SourcePackages/checkouts/**Comscore-Swift-Package-Manager**

After that we re-imported the lastest version and the problem dissapeared. Please give it a try, hopfully it you will not encoutered anymore issues in the future. 

And FYI, when using SPM package 6.7.1 you will still see 'ComScore.xcframework.zip' being downloaded inside the root of the checkout folder, as SPM clones at the latest commit, matching the time of the released version. 
Therefore the zip won't be downloaded anymore, effectively with the next release - rough timeframe is in 1-2 months.
