### ISSUE TITLE
PrivacyInfo.xprivacy compliance

### ISSUE THREAD

**Issue by hotngui** [comScore/Comscore-Swift-Package-Manager#21]
When will there be a version of the framework that includes Apple's new required privacy manifest and the SDK signature?
I am seeing calls to _mach_absolute_time, NSUserDefaults, stat, statfs_ that would reason a Reason to be specified.

**Comment by spengel** [comment]
The most recent version of our SDK already contains a Privacy Manifest that accounts for the Require Reason APIs you are referring to and has been signed.
