### ISSUE TITLE
Apple Silicon architecture support for iOS and tvOS simulators

### ISSUE THREAD

**Issue by pyby** [comScore/Comscore-Swift-Package-Manager#3]
Some of my colleagues have now a Mac with the M1 processor.

Our projects can't run on the iOS and tvOS simulators, because the arm64 simulator architectures are missing in the current 6.7.1 `xcframework` release (as described is the release notes too).

Having “arm64” in the simulator variants is what needed to run applications in simulators on an Apple Silicon Mac.

In a future version, it would be great to have In the `xcframework`:
- ios-arm64_armv7
- ios-arm64_i386_x86_64-simulator
- tvos-arm64
- tvos-arm64_x86_64-simulator

Currently:
- ios-arm64_armv7
- ios-i386_x86_64-simulator
- tvos-arm64
- tvos-x86_64-simulator

Here are some interesting articles we read for our internal frameworks:
- https://blog.embrace.io/xcode-12-and-xcframework
- https://github.com/bielikb/xcframeworks
- https://github.com/bielikb/xcframeworks#Create-xcframework-using-fastlane-plugin
- https://github.com/unsignedapps/swift-create-xcframework

Building variants with Xcode 12.3 or Xcode 12.4 makes the arm64 simulator support. We didn’t test with previous Xcode 12 versions.

Including the debug symbols (dSYMs and BCSymbolMaps) in the produced `xcframework` would also be great for few crashes we have with the framework, and helping your team when sharing the issue.

Thank you in advance for the effort to add this architecture support, helpful for iOS and tvOS developers with latest Mac devices.

**Comment by markoocko** [comment]
Hi Pierre, 
Thanks for the message. Supporting Apple Silicon architecture (simulator arm64) is actually something we've been busy with in the past weeks, alongside completly overhauling our release process to switch over to xcframeworks.
So the next release - 6.8.0 is going to encorporate all these changes. You can expect it soon, in the following weeks. 

dSYM files - symbols will not be a part of the public package, but they can be provided to our customers on demand, as we're backing them up for our crash log analysis. 

I hope this clears up all your concerns.

**Comment by pyby** [comment]
@markoocko Thanks for the [version 6.8.0](https://github.com/comScore/Comscore-Swift-Package-Manager/releases/tag/v6.8.0). The XCFramework has now the tvOS and iOS arm64 simulator architectures.

@defagos tested successfully on a MacBook Pro 13" M1 with our project and libraries. https://github.com/SRGSSR/srganalytics-apple/issues/49#issuecomment-842332599

Just a remark in the XCFramework, there are: 
- ios-arm64_armv7
- ios-arm64_i386_x86_64-simulator
- ios-i386_x86_64-simulator
- tvos-arm64
- tvos-arm64_x86_64-simulator
- tvos-x86_64-simulator

`ios-i386_x86_64-simulator` and `tvos-x86_64-simulator` could be removed, as there are not listed in the `Info.plist` and not necessary.

Could you catch it on your side for a future improvement?

Thank you to the dev team.
