### ISSUE TITLE
Binary target checksum doesn't match (since earlier today)

### ISSUE THREAD

**Issue by salling** [comScore/Comscore-Swift-Package-Manager#5]
```
checksum of downloaded artifact of binary target ‘ComScore’ (ff96f3957115afd7a63c6a9b62f790bf1ab537d4d72905cd4bbb3d58d15b74ab) does not match checksum specified by the manifest (a51398faaddab12229091c40a50ba057d74d92278591cb656a6b88dac463d89e)
```

This happens on a project that already had v6.8.0 resolved. I have tried to work around this by clearing DerivedData etc.

I don't understand why you changed the xcframework binary and checksum without bumping the package version (or release notes). I can't help but think this may be what confuses SPM. Xcode is perhaps somehow stuck in the old `v6.8.0` commit, but when it's downloading the binary xcframework, it's hitting `master` and because the version is unchanged, it's getting a version of the xcframework that doesn't have the correct checksum.

Was today's update legit? Because of the mechanism I (try to) describe above, I think you must bump the version number when releasing new bits.

**Comment by markoocko** [comment]
Hi,
I'm sorry to hear that you're facing this issue. You are correct, we updated the 6.8.0 release to remove 2 duplicated/unused frameworks from the xcframework package, as was mentioned by another user in another issue ticket. There were no other changes done e.g. all other (usable) frameworks stayed completly unchanged - as the original v6.8.0. That was the reasoning to why we didn't decide to update the version. 
We did this many times in the begining when we were testing and setting up the whole SPM enviroment and we never encountered this issue ourselves. So I'm not sure if it was just coincidence or the new versions of XCode have a different mechanism to always compare the hashes every single time when you run a project. Knowing this now, we will definetly always bump the version in the future when a hash would change.

SOLUTION:
Removing and re-adding the dependency in the SPM should fix your issue. 

Again, sorry for the inconvenience.

**Comment by salling** [comment]
Perhaps I did something wrong, but I already tried these things.

FWIW, we are seeing same issue on Travis CI, where the Xcode project is generated from scratch at every build. 

Ended up working around the issue by targeting commit hash instead of version.

**Comment by markoocko** [comment]
Hi Jonas,
I locally tested the solution in my previous comment both on an existing project and on a completly fresh one, with no issues. If you're creating a project from scratch then this points to the fact that XCode is still caching the old checkout in the XCode's DerivedData folder. Maybe you're removing the old checkout in the wrong app project? If you right click on the dependency in XCode and choose "Show in Finder" option it will take you to the exact folder, which you can then remove manually like mentioned before. Again, this should be something like this: /Users/.../Library/Developer/Xcode/DerivedData/YOUR_APP/SourcePackages/checkouts/Comscore-Swift-Package-Manager

Let us know how that goes.

**Comment by clausjoergensen** [comment]
Same issue here. Replacing a version is _always_ semantically incorrect, and you should _always_ create a minor bump, i.e. 6.8.1 when publishing a fix.

And removing the version in the DerivedData checkouts cache doesn't work in Xcode 12.5 because Apple introduced system level caching to improve the speed of SPM.

https://developer.apple.com/documentation/xcode-release-notes/xcode-12_5-release-notes

> Swift Package Manager caches package dependencies on a per-user basis, which reduces the amount of network traffic and increases performance of dependency resolution for subsequent uses of the same package. If needed, you can disable cache use in xcodebuild by using the new -disablePackageRepositoryCache flag. (72204929)

**Comment by pyby** [comment]
Same issue here.

Just removing derived data didn't work on a local machine that have already a project using ComScore 6.8.0 version. Xcode 12.5 is still comparing with the old checksum `a51398faaddab12229091c40a50ba057d74d92278591cb656a6b88dac463d89e`.

Thanks @clausjoergensen for sharing Xcode 12.5 update information.
[I found](https://developer.apple.com/forums/thread/673976) where Xcode 12.5 cache SPM repositories and manifest: `~/Library/Caches/org.swift.swiftpm/`

SOLUTION: Remove in `~/Library/Caches/org.swift.swiftpm/`, `Comscore-Swift-Package-Manager-9cad30f5.lock` file and `Comscore-Swift-Package-Manager-9cad30f5` folder. Then clean the derived datas from the current Xcode project.

I also recommend to not update a release: the delivery binary is released and delivered.

**Comment by markoocko** [comment]
Thanks for posting a workaround. We're working on creating a new release as soon as possible.

**Comment by markoocko** [comment]
Version 6.8.1 should resolve these issues. Again, apologies for any inconveniences.
